# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lucas Tiago - Portfolio
author: Lucas Tiago Santiago Silva
email: e@domain.com
avatar: lucas.jpg
description: Portfolio de Lucas Tiago| Desenvolvedor Front-end.
baseurl: "/portfolio/" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter: lucas_silva88
github:  lucastiago88
facebook: lucastiago.silva



# Build settings
markdown: kramdown
permalink: /blog/:title